// @edenup/core — MeetingManager

import type {
  Meeting,
  MeetingTopic,
  MeetingMessage,
  ActionItem,
} from './types.js'

export interface CreateMeetingOptions {
  goal: string
  initiator: string
  participants: string[]
  maxCostUsd: number
}

/**
 * Manages structured multi-agent meetings with topics, decisions,
 * escalations, and action items. Meetings are backed by messaging
 * threads and persisted to the database.
 */
export class MeetingManager {
  private meetings: Map<string, Meeting> = new Map()
  private meetingCounter = 0

  constructor() {
    // TODO: Accept MessagingAdapter[] for creating lobby messages and threads
    // TODO: Accept Database for persisting meeting state
    // TODO: Accept BudgetTracker for tracking meeting costs
  }

  /**
   * Create a new meeting, post a lobby message, and open a thread.
   * Returns the meeting object with messaging handles populated.
   */
  async create(options: CreateMeetingOptions): Promise<Meeting> {
    const id = `meeting-${++this.meetingCounter}-${Date.now()}`

    const meeting: Meeting = {
      id,
      goal: options.goal,
      initiator: options.initiator,
      participants: options.participants,
      status: 'assembling',
      topics: [],
      actionItems: [],
      budget: {
        maxCostUsd: options.maxCostUsd,
        currentCostUsd: 0,
      },
      createdAt: new Date(),
      messaging: {
        // TODO: Post lobby embed to meetings channel, capture messageId
        lobbyMessageId: '',
        // TODO: Create thread from lobby message, capture threadId
        threadId: '',
      },
    }

    this.meetings.set(id, meeting)

    // TODO: Post lobby message with meeting details using messaging adapter
    //   - Include goal, participants, status
    //   - Pin the lobby message
    // TODO: Create thread on the lobby message for the meeting discussion
    // TODO: Transition status to 'in_session' once all participants acknowledge

    meeting.status = 'in_session'
    return meeting
  }

  /**
   * Add a message to a meeting's current topic (or the general discussion).
   * Validates the sender is a participant and the meeting is in session.
   */
  async addMessage(
    meetingId: string,
    topicId: string,
    message: Omit<MeetingMessage, 'timestamp' | 'topicId'>,
  ): Promise<void> {
    const meeting = this.getMeeting(meetingId)

    if (meeting.status !== 'in_session') {
      throw new Error(`Meeting ${meetingId} is not in session (status: ${meeting.status})`)
    }

    if (!meeting.participants.includes(message.agent)) {
      throw new Error(`Agent ${message.agent} is not a participant of meeting ${meetingId}`)
    }

    const topic = meeting.topics.find((t) => t.id === topicId)
    if (!topic) {
      throw new Error(`Topic ${topicId} not found in meeting ${meetingId}`)
    }

    const fullMessage: MeetingMessage = {
      ...message,
      topicId,
      timestamp: new Date(),
    }

    topic.messages.push(fullMessage)

    // TODO: Send message to meeting thread via messaging adapter
    // TODO: Track LLM cost if this message was generated by an agent
  }

  /**
   * Mark a topic as decided with a summary of the decision.
   * Generates action items from the decision if applicable.
   */
  async decideTopic(
    meetingId: string,
    topicId: string,
    decision: string,
    actionItems: Omit<ActionItem, 'fromTopicId'>[],
  ): Promise<void> {
    const meeting = this.getMeeting(meetingId)
    const topic = this.getTopic(meeting, topicId)

    if (topic.status !== 'open') {
      throw new Error(`Topic ${topicId} is not open (status: ${topic.status})`)
    }

    topic.status = 'decided'
    topic.decision = decision

    const items: ActionItem[] = actionItems.map((item) => ({
      ...item,
      fromTopicId: topicId,
    }))

    meeting.actionItems.push(...items)

    // TODO: Post decision summary and action items to the meeting thread
    // TODO: Post a separator line in the thread via messaging adapter
  }

  /**
   * Escalate a topic to the human owner when agents cannot reach consensus.
   * Posts the escalation with context and options to the human channel.
   */
  async escalateTopic(
    meetingId: string,
    topicId: string,
    reason: string,
    options: string[],
  ): Promise<void> {
    const meeting = this.getMeeting(meetingId)
    const topic = this.getTopic(meeting, topicId)

    if (topic.status !== 'open') {
      throw new Error(`Topic ${topicId} is not open (status: ${topic.status})`)
    }

    topic.status = 'escalated'
    topic.escalation = {
      reason,
      options,
    }

    // TODO: Post escalation embed to the human/control channel
    //   - Include topic context, reason, and numbered options
    //   - Add reaction numbers for quick selection
    //   - Subscribe to reactions via onReaction()
    // TODO: Update lobby message status to reflect escalation
  }

  /**
   * Conclude the meeting, summarize decisions and action items,
   * and update the lobby message with the final summary.
   */
  async conclude(meetingId: string): Promise<Meeting> {
    const meeting = this.getMeeting(meetingId)

    if (meeting.status !== 'in_session') {
      throw new Error(`Meeting ${meetingId} is not in session (status: ${meeting.status})`)
    }

    meeting.status = 'concluded'
    meeting.concludedAt = new Date()

    // TODO: Post conclusion summary to meeting thread
    //   - List all topics with their decisions/escalation status
    //   - List all action items with assignees
    //   - Include total meeting cost
    // TODO: Update lobby message embed to show 'concluded' status
    // TODO: Persist final meeting state to database

    return meeting
  }

  /**
   * Get a meeting by ID or throw if not found.
   */
  getMeeting(meetingId: string): Meeting {
    const meeting = this.meetings.get(meetingId)
    if (!meeting) {
      throw new Error(`Meeting ${meetingId} not found`)
    }
    return meeting
  }

  /**
   * Add a new topic to an in-session meeting.
   */
  addTopic(meetingId: string, title: string, proposedBy: string): MeetingTopic {
    const meeting = this.getMeeting(meetingId)

    const topic: MeetingTopic = {
      id: `topic-${meeting.topics.length + 1}`,
      title,
      proposedBy,
      status: 'open',
      messages: [],
    }

    meeting.topics.push(topic)

    // TODO: Post topic separator embed in meeting thread

    return topic
  }

  private getTopic(meeting: Meeting, topicId: string): MeetingTopic {
    const topic = meeting.topics.find((t) => t.id === topicId)
    if (!topic) {
      throw new Error(`Topic ${topicId} not found in meeting ${meeting.id}`)
    }
    return topic
  }
}
